### ISSUE TITLE
Recursive call for createNodeCollector will result in missing paths

### ISSUE THREAD

**Issue by kevinthenet** [Botmock/utils#2]
When calling createNodeCollector, it will return a function that looks like this:

```js
function f(next, collected = []) {
    for (const { message_id } of next) {
      // If the provided intent map does not have this message id, recur with
      // this id appended to `collected`
      if (!map.has(message_id)) {
        const { next_message_ids } = getMessage(message_id);
        return f(next_message_ids, [...collected, message_id]);
      }
    }
    return collected;
  };
```

however, returning the function will result in some of the `message_id` in `next` to be visited.

**Comment by nonnontrivial** [comment]
@ortsaCniveK can you clarify what the intended behavior is?

**Comment by kevinthenet** [comment]
Sure.  If you have two branching paths from a single message without an intent in Botmock (e.g. conditional follow-up messages), you will only get one of those follow-up messages.  Intended behavior is to receive a resulting array with all collected messages, not just one branch.

If you'd like to test it you can either create a project which does that or to take a more general approach at explaining, you're returning early from a recursive call, when you want nested calls that return the simple case, which is returning the array of `collected`.

Say we have `next = [next_message_1, next_message_2]`. 

The function will start looping over items inside of `next`, pull out `message_id` from the `next_message_1`, and check it against `map`.  

Since `message_id` is not in `map`, it will get the `next_message_ids` of **`next_message_1`**, then return _out_ of function `f` with a recursive call of `f` with `collected` (at this point empty), but since we're returning inside of a for loop, we lose scope of the original function execution of `f`, and thereby `next_message_2` and all associated execution.

**Comment by nonnontrivial** [comment]
@ortsaCniveK , understood. Thank you!
